//FETCH ACTION CONSTANTS
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_RESPONSES = 'FETCH_RESPONSES';

//GET ACTION CONSTANTS
export const GET_POSTS = 'GET_POSTS';
export const GET_RESPONSES = 'GET_RESPONSES';